class AlreadyLoggedInException(Exception):
    pass


class CouldntLogInException(Exception):
    pass
